# Alias
alias cat="bat" 
alias ls="eza --color=always --long --git --icons=always --grid"
alias sz="source ~/.zshrc"
alias repo="cd ~/repo/"
alias work="cd ~/repo/work/"
alias study="cd ~/repo/study/"
alias college="cd ~/repo/college/"
alias python="python3"
alias config-zsh="nvim ~/.zshrc"
alias config-yabai="nvim ~/.config/yabai/yabairc"
alias config-skhd="nvim ~/.config/skhd/skhdrc"
alias config-sketchybar="nvim ~/.config/sketchybar/"
alias config-borders="nvim ~/.config/borders/bordersrc"
alias config-tmux="nvim ~/.config/tmux/tmux.conf"
alias config-nvim="nvim ~/.config/nvim/"
alias config-wezterm="nvim ~/.config/wezterm/"
alias config-kitty="nvim ~/.config/kitty/"
alias config-hammerspoon="nvim ~/.config/hammerspoon/"
alias config-yazi="nvim ~/.config/yazi/"
alias config-bat="nvim ~/.config/bat/config"
alias config-fzf="nvim ~/.config/fzf/fzfrc"
alias config-neovide="nvim ~/.config/neovide/config.toml"
alias config-ghostty="nvim ~/.config/ghostty/config"

eval $(thefuck --alias)
eval $(thefuck --alias fk)
