require("plugins.theme")
require("plugins.whichkey")
require("plugins.snacks")
require("plugins.treesitter")
require("plugins.neotab") -- must load before blink so Tab falls back to tabout
require("plugins.blink")
require("plugins.conform")
require("plugins.git")
require("plugins.dap")
require("plugins.grug-far")
require("plugins.markdown")
require("plugins.tiny-cmdline")
require("plugins.dropbar")
-- require("plugins.tmux")
require("plugins.harpoon")
require("plugins.trouble")
require("plugins.surround")
require("plugins.molten")
require("plugins.quarto")
require("plugins.jupytext")
require("plugins.notebook-cells")
