local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

ls.add_snippets("cpp", {
  -- Competitive-programming template
  s("competitive", {
    t({
      "#include <bits/stdc++.h>",
      "using namespace std;",
      "",
      "#define fast_io ios_base::sync_with_stdio(false); cin.tie(NULL);",
      "",
      "using ll = long long;",
      "using ull = unsigned long long;",
      "using ld = long double;",
      "using pii = pair<int, int>;",
      "using pll = pair<ll , ll>;",
      "using vi = vector<int>;",
      "using vll = vector<ll>;",
      "using vpii = vector<pii>;",
      "using vpll = vector<pll>;",
      "",
      "#define pb  push_back",
      "#define all(x)  x.begin(), x.end()",
      "#define rall(x) x.rbegin(), x.rend()",
      "#define sz(x)   (int)x.size()",
      '#define yes cout << "YES\\n"',
      '#define no  cout << "NO\\n"',
      "",
      "#ifndef ONLINE_JUDGE",
      "#define debug(x) cerr << #x << \" = \" << (x) << '\\n'",
      "#else",
      "#define debug(x)",
      "#endif",
      "",
      "ll gcd(ll a, ll b) { return b ? gcd(b, a % b) : a; }",
      "ll lcm(ll a, ll b) { return (a / gcd(a, b)) * b; }",
      "ll binpow(ll a, ll b, ll mod) {",
      "  ll res = 1;",
      "  while (b) {",
      "    if (b & 1) res = res * a % mod;",
      "    a = a * a % mod;",
      "    b >>= 1;",
      "  }",
      "  return res;",
      "}",
      "",
      "bool cmp(const pii &a, const pii &b) {",
      "  if (a.first == b.first) return a.second < b.second;",
      "  return a.first < b.first;",
      "}",
      "",
      "void solve() {",
      "  ",
      "}",
      "",
      "int main() {",
      "  fast_io;",
      "  int t = 1;",
      "  cin >> t;  // comment this if single test case",
      "  while (t--) solve();",
      "  return 0;",
      "}",
    }),
  }),

  -- print 1-D vector
  s("printvector", {
    t({
      "void printVector(const vector<int>& v) {",
      "  for (size_t i = 0; i < v.size(); ++i) {",
      "    cout << v[i] << ' ';",
      "  }",
      "  cout << '\\n';",
      "}",
    }),
  }),

  -- print 2-D vector
  s("print2dvector", {
    t({
      "void printVector2D(const vector<vector<int>>& v) {",
      "  for (size_t i = 0; i < v.size(); ++i) {",
      "    for (size_t j = 0; j < v[i].size(); ++j) {",
      "      cout << v[i][j] << ' ';",
      "    }",
      "    cout << '\\n';",
      "  }",
      "}",
    }),
  }),
})
