#!/bin/bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

#sketchybar --bar position=top height=35 blur_radius=30 color=0x40000000
sketchybar --bar position=top height=35 color=0x00000000 shadow=on

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:15.0"
  label.font="SF Pro:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
  --set chevron icon=􀣺 label.drawing=off
# --add item front_app q \
# --set front_app width=dynamic label.max_chars=0 scroll_texts=on icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
# --subscribe front_app front_app_switched

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

# SPACE_ICONS=("􀎭" "􁜿" "􀪏" "􀓕" "􀲰" "􀌥" "􀍠")
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid="$(($i+1))"
#   space=(
#     space="$sid"
#     icon="${SPACE_ICONS[i]}"
#     icon.padding_left=7
#     icon.padding_right=9
#     background.color=0x40ffffff
#     background.corner_radius=5
#     background.height=25
#     label.drawing=off
#     script="$PLUGIN_DIR/space.sh"
#     click_script="yabai -m space --focus $sid"
#   )
#   sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
# done

SPACE_ICONS=("􀎭" "􁜿" "􀪏" "􀓕" "􀲰" "􀌥" "􀍠")
sketchybar --add event aerospace_workspace_change
for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    icon="${SPACE_ICONS[sid - 1]}" \
    icon.padding_left=7 \
    icon.padding_right=9 \
    background.color=0x40ffffff \
    background.corner_radius=5 \
    background.height=25 \
    label.drawing=off \
    script="$PLUGIN_DIR/aerospace.sh $sid" \
    click_script="aerospace workspace $sid"
done

sketchybar --add item front_app q \
  --set front_app width=dynamic label.max_chars=0 scroll_texts=on icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

sketchybar --add item clock right \
  --set clock update_freq=10 icon=􀧞 script="$PLUGIN_DIR/clock.sh" \
  --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  --add item ip_address right \
  --set ip_address script="$PLUGIN_DIR/ip_address.sh" \
  update_freq=30 \
  padding_left=2 \
  padding_right=8 \
  background.border_width=0 \
  background.corner_radius=6 \
  background.height=24 \
  --subscribe ip_address wifi_change \
  --add item keyboard right \
  --set keyboard icon.drawing=off script="$PLUGIN_DIR/keyboard.sh" \
  --add event keyboard_change "AppleSelectedInputSourcesChangedNotification" \
  --subscribe keyboard keyboard_change

sketchybar --add event aerospace_workspace_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
